### ISSUE TITLE
light function 

### ISSUE THREAD

**Issue by tokkentakker** [2016-RCAD-GA-Thesis/thepit#11]
https://docs.unrealengine.com/latest/INT/Engine/Rendering/LightingAndShadows/LightFunctions/index.html

**Comment by rbaker7** [comment]
Light functions work but may be too expensive. I will take a a look at them again around polish/optimization.

**Comment by tokkentakker** [comment]
Light function for the cage?  How many do you need?

Work it out with Jamie.
Low intensity
Emissive decals may be able to sell the look as well

https://docs.unrealengine.com/latest/INT/Resources/ContentExamples/Decals/1_2/index.html

On Sep 17, 2015, at 10:58 AM, Ryan notifications@github.com wrote:

Light functions work but may be too expensive. I will take a a look at them again around polish/optimization.
